name: "Static analisis"
on: [ push ]
jobs:
  server-analisis:
    name: Server static analisis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Instal
        working-directory: ./server
        run: npm i --save-dev
      - name: Eslint analisis
        working-directory: ./server
        run: npx eslint .
      - name: Prettier
        working-directory: ./server
        run: npx prettier -c .
  client-analisis:
    name: Client static analisis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Instal
        working-directory: ./client
        run: npm i --save-dev
      - name: Eslint analisis
        working-directory: ./client
        run: npx eslint .
      - name: Prettier
        working-directory: ./client
        run: npx prettier -c .
